### ISSUE TITLE
contour plotting with decreasing axes

### ISSUE THREAD

**Issue by chriswaudby** [rafaqz/DimensionalData.jl#124] opened 2020-04-14 16:09 UTC
I've got some data where the axis values are in reverse order. When I try and do a contour plot, I get an error message:

```julia
julia> using DimensionalData, Plots
julia> x=5:-1:1;
julia> y=4:-1:1;
julia> z = [xx * yy for xx in x, yy in y];
julia> A=DimensionalArray(z,(X(x),Y(y)));
julia> contour(A)
points not sorted in ascending order
```

Plotting 1D slices of the data seems to work just fine - the problem is only with multidimensional data.

**Comment by rafaqz** [comment] 2020-04-15 03:40
This should be fixed on master. Should be registered soon too.

The issue is that plots can't plot a reverse index. So we have to flip it, but that wasn't happening properly. Be aware that this means your data will also plot in reverse as well.

If you index is in reverse but the array is forward, you can do:

```julia
A=DimensionalArray(z,(X(x; mode=Sampled(order=Ordered(index=Reverse(), relation=Reverse()))),Y(y; mode=Sampled(order=Ordered(index=Reverse(), relation=Reverse())))))
```

But that's usually only used to load 3rd party formats that happen to be like that by default.

**Comment by chriswaudby** [comment] 2020-04-15 10:35
That's done the trick, thanks!

I'm not quite sure what the distinction is between an index or array being in forward/reverse order though - would you be able to clarify this?

**Comment by rafaqz** [comment] 2020-04-16 03:56
Ok I guess I need to document this better!

The index in reverse means it is sorted desending. That's important to track for using `searchsortedfirst` and for plotting as you found out. But we can also auto detect it so you don't need to think about it much.

Having the `relation` in reverse mean the first index value matches the last array value - they have a reversed relationship. This definitely happens sometimes. But you need to set it manually. Usually it's just standard for some interface that extends DD for a data source, not user-set.

The array in reverse means it should be plotted backwards. Which is also common. But plots needs the index to be forwards, so the array order does nothing in practice. Mostly this is fine as that's how it should be plotted anyway. But if there is a way to have the axes in descending order in Plots.jl then we can have the index descending and the array the right way around. I just haven't had to actually deal with that use case in practice yet.

**Closed** 2020-04-17 14:03 UTC
Labels: bug
