### ISSUE TITLE
Call for the quantile function in Statistics

### ISSUE THREAD

**Issue by kongdd** [rafaqz/DimensionalData.jl#370] opened 2022-03-24 08:22 UTC
`quantile` also is very frequently used function. 
Any idea how to make it in `DD`?

**Comment by kongdd** [comment] 2022-03-24 08:41
A weird result. 
The following scripts works for quantile. But when I change the dimname from `z` to `Z` (as well as the `dimnames_default `), error jumps.

```julia
using DimensionalData
using Random

const TYPE_dimname = Union{Symbol,AbstractString}
# const dimnames_default = ["X", "Y", "Z", "Ti"]
const dimnames_default = ["x", "y", "z", "t"]

function make_tuple(vals::Vector, names::Vector{<:TYPE_dimname})
  (; zip(Symbol.(names), vals)...)
end
function make_tuple(val, name::TYPE_dimname)
  make_tuple([val], [name])
end

function make_dims(array::AbstractArray, dimnames = dimnames_default)
  n = size(array) |> length
  length(dimnames) < n && error("The length of `names` is short than `dims`")
  Size = size(array)
  dimnames = Symbol.(dimnames)
  
  [Dim{dimnames[i]}(1:Size[i]) for i in 1:length(Size)]
  # vals = [1:i for i in Size] |> collect
  # make_tuple(vals, dimnames[1:n])
end

function DimensionalData.DimArray(array::AbstractArray, 
  dimnames::Vector{<:TYPE_dimname} = dimnames_default; kw...)
  
  dims = make_dims(array, dimnames)
  DimArray(array, Tuple(dims), kw...) # 
end
  
if 0
  # test for `make_tuple` 
  vals = [1:4]
  make_tuple(vals, ["x"])
  make_tuple(vals, [:x])
  make_tuple(vals[1], :x)
  make_tuple(vals[1], "x")

  make_dims(rand(2, 2))
end

## Test about quantile
begin
  using Statistics
  arr = rand(10, 10, 365, 5)
  d = DimArray(arr)
  d.dims
  ## mapslices (in Julia) = apply (R) 
  # r1 = mapslices(x -> quantile(x, [0.1, 0.5]), arr; dims = 3)
  # r2 = mapslices(x -> quantile(x, [0.1, 0.5]), d; dims = Symbol("Z"))
  # r2 = mapslices(x -> quantile(x, [0.1, 0.5]), d; dims = Dim{:Z})
  r2 = mapslices(x -> quantile(x, [0.1, 0.5]), d; dims = :z)
end
```

**Comment by kongdd** [comment] 2022-03-24 08:47
The error message: 

```julia
julia>   r2 = mapslices(x -> quantile(x, [0.1, 0.5]), d; dims = :Z)

ERROR: ArgumentError: Some dims were not found in object
Stacktrace:
 [1] _errorextradims()
   @ DimensionalData.Dimensions ~/.julia/packages/DimensionalData/jl2xf/src/Dimensions/primitives.jl:596
 [2] dimnum
   @ ~/.julia/packages/DimensionalData/jl2xf/src/Dimensions/primitives.jl:198 [inlined]
 [3] mapslices(f::Function, A::DimArray{Float64, 4, Tuple{Dim{:x, DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Dim{:y, DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Dim{:z, DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Dim{:T, DimensionalData.Dimensions.LookupArrays.Sampled{Int64, UnitRange{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Tuple{}, Array{Float64, 4}, DimensionalData.NoName, DimensionalData.Dimensions.LookupArrays.NoMetadata}; dims::Symbol, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ DimensionalData ~/.julia/packages/DimensionalData/jl2xf/src/array/methods.jl:102
 [4] top-level scope
   @ /mnt/i/GitHub/geo-julia/nctools.jl/scripts/scripts/test/test-dimArray.jl:54
```

**Comment by rafaqz** [comment] 2022-03-24 08:48
`Dim{:Z}` is the problem, because the dimension type `Z` is defined already, so you will get a dimension mismatch if you use dims=:Z. It will look for the type `Z` instead. 

Maybe it should look for both and they should be equivalent? I have been wondering if people would have issues with this.

But this is nothing to do with `quantile` - the problem is in `mapslices`.

**Comment by rafaqz** [comment] 2022-03-24 08:50
The reason to have `X` `Y` `Z` types defined is because they are much easier to use and read as wrapper types than `Dim{:Z}`. But its a little complicated.

**Comment by kongdd** [comment] 2022-03-24 08:56
I am trying to find a way to automatically assign the dimension name and dimension value (the function `make_dims` does). 

If the used the default X, Y, Z, Ti, I have to know their length in advance. It is less convenient.
Sometimes, users just want the dimension names.

**Comment by rafaqz** [comment] 2022-03-24 09:05
I don't totally understand what you can do here. 

But I agree, we should make `Dim{:Z}` equivalent to `Z`. It's a small change, and not even breaking because currently it causes errors.

**Comment by kongdd** [comment] 2022-03-24 09:23
It will be great if this problem can be solved.

**Comment by kongdd** [comment] 2022-03-24 09:37
Just found another issue of `mapslices`. The dimension is incorrect.

```julia
using Statistics
using DimensionalData

function make_dims(array::AbstractArray, dimnames::Vector{<:TYPE_dimname} = dimnames_default)
  n = size(array) |> length
  length(dimnames) < n && error("The length of `names` is short than `dims`")
  Size = size(array)
  dimnames = Symbol.(dimnames)
  
  [Dim{dimnames[i]}(1:Size[i]) for i in 1:length(Size)]
  # vals = [1:i for i in Size] |> collect
  # make_tuple(vals, dimnames[1:n])
end

function DimensionalData.DimArray(array::AbstractArray, 
  dimnames::Vector{<:TYPE_dimname} = dimnames_default; kw...)
  
  dims = make_dims(array, dimnames)
  DimArray(array, Tuple(dims), kw...) # 
end

arr = rand(10, 10, 365, 5);
d = DimArray(arr)

probs = [0.5, 0.9];
mapslices(x -> quantile(x, probs), d, dims = 3)
```
![image](https://user-images.githubusercontent.com/9815742/159887250-bd8d4cf2-9ac3-4a6a-84a5-bbc24115d246.png)

**Comment by rafaqz** [comment] 2022-03-24 10:54
Can you post your examples as text rather than images? I cant run that without typing.

And maybe write what the expected result should be, e.g. comparing to a regular array?

**Comment by rafaqz** [comment] 2022-03-24 12:19
First, this simplifies your code:

```julia
using Statistics
using DimensionalData

const DIMNAMES = (X, Y, Z, Ti)

function make_dims(A::AbstractArray, dimnames)
    length(dimnames) < ndims(A) && error("The length of `names` is short than `dims`")
    map(ntuple(identity, ndims(A))) do i
        dimnames[i](1:size(A, i))
    end
end

dimarray(A::AbstractArray, dimnames=DIMNAMES; kw...) = DimArray(A, make_dims(A, dimnames), kw...) 

arr = rand(10, 10, 365, 5)
d = dimarray(arr)

```

**Comment by rafaqz** [comment] 2022-03-24 12:21
But for a MWE, this is better:

```julia
A = rand(X(10), Y(10), Z(365), Ti(5))
d = dimarray(A)
probs = [0.5, 0.9];
mapslices(x -> quantile(x, probs), d, dims=3)
```

With the result:

```julia
julia> mapslices(x -> quantile(x, probs), d, dims=3)
10×10×2×5 DimArray{Float64,4} with dimensions:
  X Sampled 1:10 ForwardOrdered Regular Points,
  Y Sampled 1:10 ForwardOrdered Regular Points,
  Z Sampled 1:365 ForwardOrdered Regular Points,
  Ti Sampled 1:5 ForwardOrdered Regular Points
[:, :, 1, 1]
 0.512683  0.512156  0.489545  0.48212   …  0.494349  0.482514  0.458855  0.51653
 0.505904  0.527684  0.487739  0.497044     0.48116   0.498431  0.527005  0.524983
 0.447418  0.493867  0.51785   0.468488     0.496832  0.482698  0.464582  0.518256
 0.493333  0.453332  0.512729  0.508516     0.501797  0.520225  0.515852  0.51857
 0.50898   0.522829  0.501801  0.540445     0.460889  0.444496  0.514151  0.517045
 0.494221  0.502176  0.452527  0.483545  …  0.511854  0.513878  0.527968  0.474323
 0.47034   0.484794  0.53423   0.512974     0.513608  0.531333  0.514065  0.508143
 0.507987  0.525465  0.461232  0.472248     0.512965  0.520082  0.491199  0.505499
 0.511709  0.515658  0.460854  0.494408     0.505485  0.484747  0.500367  0.538699
 0.520557  0.491696  0.529733  0.474733     0.510195  0.483797  0.492762  0.530763
[and 9 more slices...]
```

**Comment by rafaqz** [comment] 2022-03-24 12:25
And I can see the problem is the Z dimension.

There are 2 reasons for this. First, `mapslices` passes a regular `Array` to `qantiles`. It should pass a `DimArray`. That's easy to fix.

Second, `quantiles` doesn't fix the index of a `DimArray`. This is hard. How do we know which values where used? we probably have to use `selectindices(A, At(val))` for all the returned values in the vector. Or rewrite a custom `_quantiles` method so it returns the indices rather than the values (or a `index => value` pair), and use those.

**Comment by rafaqz** [comment] 2022-03-24 12:35
Maybe, to fix this in a generic way that would also work for `sort` and other methods that currently don't work, we would need to wrap all the values in an object that also holds the index value.

So an object like this:

```julia
struct IndexedNumber <: AbstractNumbers.AbstractNumber
    number::V
    dimval::DV
end
AbstractNumbers.number(x::InexedNumber) = x.number
```

Then we can run `quantile` or `sort` on a vector of these and they will keep their index values, which we can separate out again to rebuild the correct `DimArray`.

Do you think it is worth doing this?

**Comment by rafaqz** [comment] 2022-03-24 12:40
Also, cant `quantile` be different for each of the slices ? 

Probably `mapslices` should just set the `Z` dimension to be `NoIndex`, because we just don't know what it is anymore.

**Comment by rafaqz** [comment] 2024-02-01 15:11
`quantile` is really hard to implement for DimArray and not widely enough used. If someone wants to try an implementation, go for it. But I will close this for now.

**Closed by rafaqz** 2024-02-01 15:11 UTC
